# Generated by Django 3.2.8 on 2022-08-10 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=400)),
                ('difficultyLvl', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='Easy', max_length=6)),
                ('views', models.IntegerField(default=0)),
                ('QuizImg', models.ImageField(upload_to='QuizImage/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('ansA', models.CharField(max_length=250)),
                ('ansB', models.CharField(max_length=250)),
                ('ansC', models.CharField(max_length=250)),
                ('ansD', models.CharField(max_length=250)),
                ('correctAns', models.CharField(max_length=250)),
                ('questionImg', models.ImageField(upload_to='QuestionImages/')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApi.quizmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteQuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApi.quizmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
