# Generated by Django 3.2.8 on 2022-08-10 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0002_alter_questionmodel_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(upload_to='CategoryIcon/')),
            ],
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='difficultyLvl',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Hard', 'Hard'), ('Easy', 'Easy')], default='Easy', max_length=6),
        ),
    ]
