# Generated by Django 3.2.8 on 2022-08-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0004_alter_quizmodel_difficultylvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='cateogry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainApi.quizcategorymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='difficultyLvl',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Hard', 'Hard'), ('Easy', 'Easy')], default='Easy', max_length=6),
        ),
    ]
