# Generated by Django 3.2.8 on 2022-08-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0006_auto_20220810_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='difficultyLvl',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Easy', 'Easy'), ('Hard', 'Hard')], default='Easy', max_length=6),
        ),
    ]
