# Generated by Django 3.2.8 on 2022-08-11 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApi', '0007_alter_quizmodel_difficultylvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritequizmodel',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizmodel', to='MainApi.quizmodel'),
        ),
        migrations.AlterField(
            model_name='favoritequizmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermodel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='difficultyLvl',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Hard', 'Hard'), ('Medium', 'Medium')], default='Easy', max_length=6),
        ),
    ]
