# Generated by Django 3.2.8 on 2022-08-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0008_auto_20220811_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='difficultyLvl',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=6),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='views',
            field=models.FloatField(default=0),
        ),
    ]
