# Generated by Django 3.2.8 on 2023-02-26 19:50

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0009_auto_20220811_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='questionImgAlt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='quizcategorymodel',
            name='iconAlt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='QuizImgAlt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='questionImg',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='QuestionImages/'),
        ),
        migrations.AlterField(
            model_name='quizcategorymodel',
            name='icon',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='CategoryIcon/'),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='QuizImg',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='QuizImage/'),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='difficultyLvl',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Easy', 'Easy'), ('Hard', 'Hard')], default='Easy', max_length=6),
        ),
    ]
